Daica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic.urls',namespace = 'home'))
]

basic/urls.py
from re import template
from django.urls import path, include

from . import views

from django.views.generic import TemplateView



app_name = 'basic'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

basic/views.py
from django.views import generic


class HomeView(generic.ListView):
    template_name = 'basic/home.html'
    def get_queryset(self):
        return 0

basic/templates/basic/base.html
<!-- base formula by https://stackoverflow.com/questions/14720464/django-project-base-template-->

<!DOCTYPE html>
{% load static %}
<!-- https://docs.djangoproject.com/en/4.0/intro/tutorial06/ -->
<link rel="stylesheet" type="text/css" href="{% static 'basic/style.css' %}">
{% load bootstrap5 %}



{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!-- Navbar https://epicbootstrap.com/snippets/header-blue-->
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daica</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
    <link rel="stylesheet" href="assets/css/style.css">
</head>

<body>
    <div>
        <div class="header-blue">
            <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">
                <div class="container"><a class="navbar-brand" href="{%url 'basic:home'%}">Daica</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                        id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link active" href="#">Theaters</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link active" href="#">Scheduler</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link active" href="#">Chat</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link active" href="#">Search</a></li>

                        </ul>
                        <form class="form-inline mr-auto" target="_self">
                            <!-- <div class="form-group"><label for="search-field"><i class="fa fa-search"></i></label><input class="form-control search-field" type="search" name="search" id="search-field"></div> -->
                        </form><span class="navbar-text"> <a href="/accounts/login" class="login">Log In</a></span><a class="btn btn-light action-button" role="button" href="#">Sign Up</a></div>
                </div>
            </nav>
            <div class="container hero">
                <div class="row">
                    {%block content%}{%endblock content%}
                </div>

            </div>
        </div>
    </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</body>

</html>

<!-- Navbar -->

basic/templates/basic/home.html
<!--# citation: https://www.w3schools.com/tags/tag_li.asp -->
<!--# https://www.w3schools.com/html/html_links.asp -->

<!DOCTYPE html>
{% extends "basic/base.html" %}

{% load static %}
{% load bootstrap5 %}



{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}


{% block content %} <!--https://epicbootstrap.com/snippets/header-blue-->
<div class="col-12 col-lg-6 col-xl-5 offset-xl-1">
    <h1></h1>
    <p>Schedule watch parties, cinema trips and more! Share your love for TV shows and movies with your friends. Log in to get started</p>
</div>

{% endblock content %}